CC = gcc
CFLAGS = -Wall -Werror -Wextra -g

DEP = ../../src/display.c ../../src/display.h
SRC = ../../src/display.c

test_display: test_display.c $(DEP)
	$(CC) $(CFLAGS) $(SRC) test_display.c -o test_display
